// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: dashv3

#include "../ui.h"

lv_obj_t * uic_fuelslider;
lv_obj_t * uic_fuel;
lv_obj_t * uic_fuelscale;
lv_obj_t * uic_parkingbrake;
lv_obj_t * uic_turnsignal;
lv_obj_t * uic_watertemp;
lv_obj_t * uic_checkengine;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_TopPanel = NULL;
lv_obj_t * ui_RPM = NULL;
lv_obj_t * ui_rpmbg = NULL;
lv_obj_t * ui_rpmslider = NULL;
lv_obj_t * ui_rpmscale = NULL;
lv_obj_t * ui_Speed = NULL;
lv_obj_t * ui_checkengine = NULL;
lv_obj_t * ui_watertemp = NULL;
lv_obj_t * ui_turnsignal = NULL;
lv_obj_t * ui_parkingbrake = NULL;
lv_obj_t * ui_fuelscale = NULL;
lv_obj_t * ui_fuel = NULL;
lv_obj_t * ui_fuelslider = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_TopPanel, 800);
    lv_obj_set_height(ui_TopPanel, 480);
    lv_obj_set_align(ui_TopPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TopPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TopPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM = lv_obj_create(ui_TopPanel);
    lv_obj_set_width(ui_RPM, 800);
    lv_obj_set_height(ui_RPM, 480);
    lv_obj_set_align(ui_RPM, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RPM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmbg = lv_img_create(ui_RPM);
    lv_img_set_src(ui_rpmbg, &ui_img_rpmbackground_png);
    lv_obj_set_width(ui_rpmbg, 800);
    lv_obj_set_height(ui_rpmbg, 480);
    lv_obj_set_x(ui_rpmbg, 0);
    lv_obj_set_y(ui_rpmbg, 1);
    lv_obj_set_align(ui_rpmbg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rpmbg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rpmbg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rpmbg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_rpmbg, lv_color_hex(0x770707), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmslider = lv_arc_create(ui_rpmbg);
    lv_obj_set_width(ui_rpmslider, lv_pct(80));
    lv_obj_set_height(ui_rpmslider, lv_pct(89));
    lv_obj_set_x(ui_rpmslider, 107);
    lv_obj_set_y(ui_rpmslider, 2);
    lv_obj_set_align(ui_rpmslider, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_rpmslider, 0, 8000);
    //lv_arc_set_value(ui_rpmslider, 8000);
    lv_obj_set_style_radius(ui_rpmslider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmslider, lv_color_hex(0xDC1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmslider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_rpmslider, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_rpmslider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_rpmslider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmslider, lv_color_hex(0x0D209F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmslider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rpmslider, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rpmslider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_rpmslider, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_rpmslider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_rpmslider, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_rpmslider, &ui_img_rpmfront_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_rpmslider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmslider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_rpmscale = lv_img_create(ui_RPM);
    lv_img_set_src(ui_rpmscale, &ui_img_rpmdial_png);
    lv_obj_set_width(ui_rpmscale, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmscale, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rpmscale, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rpmscale, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rpmscale, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Speed = lv_label_create(ui_RPM);
    lv_obj_set_width(ui_Speed, 800);
    lv_obj_set_height(ui_Speed, 46);
    lv_obj_set_align(ui_Speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speed, "150");
    lv_obj_set_style_text_color(ui_Speed, lv_color_hex(0xFDFDFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Speed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Speed, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_checkengine = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_checkengine, &ui_img_checkengine_png);
    lv_obj_set_width(ui_checkengine, 100);
    lv_obj_set_height(ui_checkengine, 100);
    lv_obj_set_x(ui_checkengine, -339);
    lv_obj_set_y(ui_checkengine, 182);
    lv_obj_set_align(ui_checkengine, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_checkengine, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_checkengine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_checkengine, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_checkengine, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watertemp = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_watertemp, &ui_img_watertemp_png);
    lv_obj_set_width(ui_watertemp, 100);
    lv_obj_set_height(ui_watertemp, 100);
    lv_obj_set_x(ui_watertemp, -342);
    lv_obj_set_y(ui_watertemp, -182);
    lv_obj_set_align(ui_watertemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watertemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_watertemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_watertemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_watertemp, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_turnsignal = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_turnsignal, &ui_img_turnsignal_png);
    lv_obj_set_width(ui_turnsignal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_turnsignal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_turnsignal, 0);
    lv_obj_set_y(ui_turnsignal, 195);
    lv_obj_set_align(ui_turnsignal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_turnsignal, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_turnsignal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_turnsignal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_turnsignal, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_parkingbrake = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_parkingbrake, &ui_img_parkingbrake_png);
    lv_obj_set_width(ui_parkingbrake, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_parkingbrake, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_parkingbrake, 345);
    lv_obj_set_y(ui_parkingbrake, 201);
    lv_obj_set_align(ui_parkingbrake, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_parkingbrake, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_parkingbrake, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_parkingbrake, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_parkingbrake, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelscale = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_fuelscale, &ui_img_322054780);
    lv_obj_set_width(ui_fuelscale, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fuelscale, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fuelscale, 316);
    lv_obj_set_y(ui_fuelscale, -220);
    lv_obj_set_align(ui_fuelscale, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fuelscale, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fuelscale, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fuel = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_fuel, &ui_img_fuel_png);
    lv_obj_set_width(ui_fuel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fuel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fuel, 313);
    lv_obj_set_y(ui_fuel, -193);
    lv_obj_set_align(ui_fuel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fuel, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fuel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fuelslider = lv_slider_create(ui_Screen1);
    lv_slider_set_value(ui_fuelslider, 25, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_fuelslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_fuelslider, 100, LV_ANIM_OFF);
    lv_obj_set_width(ui_fuelslider, 146);
    lv_obj_set_height(ui_fuelslider, 31);
    lv_obj_set_x(ui_fuelslider, 307);
    lv_obj_set_y(ui_fuelslider, -178);
    lv_obj_set_align(ui_fuelslider, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_fuelslider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_fuelslider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fuelslider, lv_color_hex(0xEED629), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuelslider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_fuelslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuelslider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    uic_checkengine = ui_checkengine;
    uic_watertemp = ui_watertemp;
    uic_turnsignal = ui_turnsignal;
    uic_parkingbrake = ui_parkingbrake;
    uic_fuelscale = ui_fuelscale;
    uic_fuel = ui_fuel;
    uic_fuelslider = ui_fuelslider;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_TopPanel = NULL;
    ui_RPM = NULL;
    ui_rpmbg = NULL;
    ui_rpmslider = NULL;
    ui_rpmscale = NULL;
    ui_Speed = NULL;
    uic_checkengine = NULL;
    ui_checkengine = NULL;
    uic_watertemp = NULL;
    ui_watertemp = NULL;
    uic_turnsignal = NULL;
    ui_turnsignal = NULL;
    uic_parkingbrake = NULL;
    ui_parkingbrake = NULL;
    uic_fuelscale = NULL;
    ui_fuelscale = NULL;
    uic_fuel = NULL;
    ui_fuel = NULL;
    uic_fuelslider = NULL;
    ui_fuelslider = NULL;

}
