// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TopPanel;
extern lv_obj_t * ui_RPM;
extern lv_obj_t * ui_rpmbg;
extern lv_obj_t * ui_rpmslider;
extern lv_obj_t * ui_rpmscale;
extern lv_obj_t * ui_Speed;
extern lv_obj_t * ui_checkengine;
extern lv_obj_t * ui_watertemp;
// CUSTOM VARIABLES
extern lv_obj_t * uic_checkengine;
extern lv_obj_t * uic_watertemp;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

