// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1;
lv_obj_t * ui_TopPanel;
lv_obj_t * ui_RPM;
lv_obj_t * ui_rpmbg;
lv_obj_t * ui_rpmslider;
lv_obj_t * ui_rpmscale;
lv_obj_t * ui_Speed;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Image3;

// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_TopPanel, 800);
    lv_obj_set_height(ui_TopPanel, 480);
    lv_obj_set_align(ui_TopPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TopPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TopPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM = lv_obj_create(ui_TopPanel);
    lv_obj_set_width(ui_RPM, 800);
    lv_obj_set_height(ui_RPM, 480);
    lv_obj_set_align(ui_RPM, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RPM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmbg = lv_img_create(ui_RPM);
    lv_img_set_src(ui_rpmbg, &ui_img_rpmbackground_png);
    lv_obj_set_width(ui_rpmbg, 800);
    lv_obj_set_height(ui_rpmbg, 480);
    lv_obj_set_x(ui_rpmbg, 0);
    lv_obj_set_y(ui_rpmbg, 1);
    lv_obj_set_align(ui_rpmbg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rpmbg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rpmbg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rpmbg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_rpmbg, lv_color_hex(0x770707), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmslider = lv_arc_create(ui_rpmbg);
    lv_obj_set_width(ui_rpmslider, lv_pct(80));
    lv_obj_set_height(ui_rpmslider, lv_pct(89));
    lv_obj_set_x(ui_rpmslider, 107);
    lv_obj_set_y(ui_rpmslider, 2);
    lv_obj_set_align(ui_rpmslider, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_rpmslider, 0, 8000);
    lv_arc_set_value(ui_rpmslider, 8000);
    lv_obj_set_style_radius(ui_rpmslider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmslider, lv_color_hex(0xDC1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmslider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_rpmslider, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_rpmslider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_rpmslider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmslider, lv_color_hex(0x0D209F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmslider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rpmslider, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rpmslider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_rpmslider, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_rpmslider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_rpmslider, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_rpmslider, &ui_img_rpmfront_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_rpmslider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmslider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_rpmscale = lv_img_create(ui_RPM);
    lv_img_set_src(ui_rpmscale, &ui_img_rpmdial_png);
    lv_obj_set_width(ui_rpmscale, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmscale, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rpmscale, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rpmscale, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rpmscale, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Speed = lv_label_create(ui_RPM);
    lv_obj_set_width(ui_Speed, 800);
    lv_obj_set_height(ui_Speed, 46);
    lv_obj_set_align(ui_Speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speed, "150");
    lv_obj_set_style_text_color(ui_Speed, lv_color_hex(0xFDFDFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Speed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Speed, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_checkengine_png);
    lv_obj_set_width(ui_Image2, 100);
    lv_obj_set_height(ui_Image2, 100);
    lv_obj_set_x(ui_Image2, -339);
    lv_obj_set_y(ui_Image2, 182);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_watertemp_png);
    lv_obj_set_width(ui_Image3, 100);
    lv_obj_set_height(ui_Image3, 100);
    lv_obj_set_x(ui_Image3, -342);
    lv_obj_set_y(ui_Image3, -182);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_TopPanel = NULL;
    ui_RPM = NULL;
    ui_rpmbg = NULL;
    ui_rpmslider = NULL;
    ui_rpmscale = NULL;
    ui_Speed = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;

}
