// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 4.3btest

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_screen;
extern lv_obj_t * ui_rpmscale;
extern lv_obj_t * ui_rpmslider;
extern lv_obj_t * ui_RPM;
extern lv_obj_t * ui_CheckEngine;
extern lv_obj_t * ui_DSC;
extern lv_obj_t * ui_fuel;
extern lv_obj_t * ui_water;
extern lv_obj_t * ui_fuelbar;
extern lv_obj_t * ui_TurnSignal;
extern lv_obj_t * ui_Speed;
extern lv_obj_t * ui_ParkingBrake;
// CUSTOM VARIABLES
extern lv_obj_t * uic_rpmslider;
extern lv_obj_t * uic_RPM;
extern lv_obj_t * uic_CheckEngine;
extern lv_obj_t * uic_DSC;
extern lv_obj_t * uic_fuel;
extern lv_obj_t * uic_water;
extern lv_obj_t * uic_fuelbar;
extern lv_obj_t * uic_TurnSignal;
extern lv_obj_t * uic_Speed;
extern lv_obj_t * uic_ParkingBrake;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

