// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 4.3btest

#include "../ui.h"

lv_obj_t * uic_ParkingBrake;
lv_obj_t * uic_Speed;
lv_obj_t * uic_TurnSignal;
lv_obj_t * uic_fuelbar;
lv_obj_t * uic_water;
lv_obj_t * uic_fuel;
lv_obj_t * uic_DSC;
lv_obj_t * uic_CheckEngine;
lv_obj_t * uic_RPM;
lv_obj_t * uic_rpmslider;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_screen = NULL;
lv_obj_t * ui_rpmscale = NULL;
lv_obj_t * ui_rpmslider = NULL;
lv_obj_t * ui_RPM = NULL;
lv_obj_t * ui_CheckEngine = NULL;
lv_obj_t * ui_DSC = NULL;
lv_obj_t * ui_fuel = NULL;
lv_obj_t * ui_water = NULL;
lv_obj_t * ui_fuelbar = NULL;
lv_obj_t * ui_TurnSignal = NULL;
lv_obj_t * ui_Speed = NULL;
lv_obj_t * ui_ParkingBrake = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screen = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_screen);
    lv_obj_set_width(ui_screen, 800);
    lv_obj_set_height(ui_screen, 480);
    lv_obj_set_align(ui_screen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_screen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmscale = lv_img_create(ui_screen);
    lv_img_set_src(ui_rpmscale, &ui_img_rpmdial_png);
    lv_obj_set_width(ui_rpmscale, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmscale, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmscale, 1);
    lv_obj_set_y(ui_rpmscale, -2);
    lv_obj_set_align(ui_rpmscale, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rpmscale, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rpmscale, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rpmslider = lv_arc_create(ui_screen);
    lv_obj_set_width(ui_rpmslider, 379);
    lv_obj_set_height(ui_rpmslider, 379);
    lv_obj_set_x(ui_rpmslider, -2);
    lv_obj_set_y(ui_rpmslider, 30);
    lv_obj_set_align(ui_rpmslider, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_rpmslider, 0, 10000);
    lv_arc_set_value(ui_rpmslider, 500);
    lv_obj_set_style_arc_color(ui_rpmslider, lv_color_hex(0xA6A6F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_rpmslider, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_rpmslider, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_rpmslider, lv_color_hex(0xFF4040), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_rpmslider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_rpmslider, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_rpmslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmslider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_RPM = lv_label_create(ui_screen);
    lv_obj_set_width(ui_RPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPM, 0);
    lv_obj_set_y(ui_RPM, -200);
    lv_obj_set_align(ui_RPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPM, "RPM");
    lv_obj_set_style_text_color(ui_RPM, lv_color_hex(0xE40F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPM, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckEngine = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_CheckEngine, &ui_img_checkengine_png);
    lv_obj_set_width(ui_CheckEngine, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckEngine, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckEngine, -343);
    lv_obj_set_y(ui_CheckEngine, 51);
    lv_obj_set_align(ui_CheckEngine, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckEngine, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CheckEngine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DSC = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_DSC, &ui_img_dcs_png);
    lv_obj_set_width(ui_DSC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DSC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DSC, 346);
    lv_obj_set_y(ui_DSC, 26);
    lv_obj_set_align(ui_DSC, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DSC, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_DSC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fuel = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_fuel, &ui_img_fuel_png);
    lv_obj_set_width(ui_fuel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fuel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fuel, 310);
    lv_obj_set_y(ui_fuel, -188);
    lv_obj_set_align(ui_fuel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fuel, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fuel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_water = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_water, &ui_img_watertemp_png);
    lv_obj_set_width(ui_water, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_water, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_water, 0);
    lv_obj_set_y(ui_water, 14);
    lv_obj_set_align(ui_water, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_water, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_water, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_water, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_water, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelbar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_fuelbar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_fuelbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_fuelbar, 126);
    lv_obj_set_height(ui_fuelbar, 25);
    lv_obj_set_x(ui_fuelbar, 306);
    lv_obj_set_y(ui_fuelbar, -175);
    lv_obj_set_align(ui_fuelbar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_fuelbar, lv_color_hex(0xD8DF23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuelbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_fuelbar, lv_color_hex(0x900E0E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuelbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_TurnSignal = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_TurnSignal, &ui_img_turnsignal_png);
    lv_obj_set_width(ui_TurnSignal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TurnSignal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TurnSignal, 0);
    lv_obj_set_y(ui_TurnSignal, 185);
    lv_obj_set_align(ui_TurnSignal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TurnSignal, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TurnSignal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Speed = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Speed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Speed, 0);
    lv_obj_set_y(ui_Speed, 6);
    lv_obj_set_align(ui_Speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speed, "Speed");
    lv_obj_set_style_text_color(ui_Speed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Speed, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ParkingBrake = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ParkingBrake, &ui_img_parkingbrake_png);
    lv_obj_set_width(ui_ParkingBrake, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParkingBrake, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParkingBrake, -200);
    lv_obj_set_y(ui_ParkingBrake, -200);
    lv_obj_set_align(ui_ParkingBrake, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ParkingBrake, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ParkingBrake, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_rpmslider = ui_rpmslider;
    uic_RPM = ui_RPM;
    uic_CheckEngine = ui_CheckEngine;
    uic_DSC = ui_DSC;
    uic_fuel = ui_fuel;
    uic_water = ui_water;
    uic_fuelbar = ui_fuelbar;
    uic_TurnSignal = ui_TurnSignal;
    uic_Speed = ui_Speed;
    uic_ParkingBrake = ui_ParkingBrake;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_screen = NULL;
    ui_rpmscale = NULL;
    uic_rpmslider = NULL;
    ui_rpmslider = NULL;
    uic_RPM = NULL;
    ui_RPM = NULL;
    uic_CheckEngine = NULL;
    ui_CheckEngine = NULL;
    uic_DSC = NULL;
    ui_DSC = NULL;
    uic_fuel = NULL;
    ui_fuel = NULL;
    uic_water = NULL;
    ui_water = NULL;
    uic_fuelbar = NULL;
    ui_fuelbar = NULL;
    uic_TurnSignal = NULL;
    ui_TurnSignal = NULL;
    uic_Speed = NULL;
    ui_Speed = NULL;
    uic_ParkingBrake = NULL;
    ui_ParkingBrake = NULL;

}
