// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 4.3btest

#ifndef _UI_COMP_RPMSLIDER_H
#define _UI_COMP_RPMSLIDER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT rpmslider
#define UI_COMP_RPMSLIDER_RPMSLIDER 0
#define _UI_COMP_RPMSLIDER_NUM 1
lv_obj_t * ui_rpmslider_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
