// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: waveshare43-minimal

#ifndef UI_SECONDSCREEN_H
#define UI_SECONDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SecondScreen
extern void ui_SecondScreen_screen_init(void);
extern void ui_SecondScreen_screen_destroy(void);
extern lv_obj_t * ui_SecondScreen;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

