// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: waveshare43-minimal

#include "../ui.h"

lv_obj_t * ui_SecondScreen;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label2;

// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FirstScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_FirstScreen_screen_init);
    }
}

// build funtions

void ui_SecondScreen_screen_init(void)
{
    ui_SecondScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SecondScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_SecondScreen);
    lv_obj_set_width(ui_Button2, 255);
    lv_obj_set_height(ui_Button2, 174);
    lv_obj_set_x(ui_Button2, 176);
    lv_obj_set_y(ui_Button2, 0);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Button2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Go to\nfirst screen");
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}

void ui_SecondScreen_screen_destroy(void)
{
    if(ui_SecondScreen) lv_obj_del(ui_SecondScreen);

    // NULL screen variables
    ui_SecondScreen = NULL;
    ui_Button2 = NULL;
    ui_Label2 = NULL;

}
