// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 4.3btest

#include "../ui.h"

lv_obj_t * uic_RPM;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_RPM = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_RPM, 150);
    lv_obj_set_height(ui_RPM, 150);
    lv_obj_set_align(ui_RPM, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_RPM, 0, 10000);
    lv_arc_set_value(ui_RPM, 500);

    lv_obj_set_style_arc_color(ui_RPM, lv_color_hex(0xFF407B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RPM, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RPM, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    uic_RPM = ui_RPM;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_RPM = NULL;
    ui_RPM = NULL;

}
