// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_IMGBUTTON1_H
#define _UI_COMP_IMGBUTTON1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ImgButton1
#define UI_COMP_IMGBUTTON1_IMGBUTTON1 0
#define _UI_COMP_IMGBUTTON1_NUM 1
lv_obj_t * ui_ImgButton1_create(lv_obj_t * comp_parent);
void ui_event_comp_ImgButton1_ImgButton1(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
