// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_event_comp_ImgButton1_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ImgButton1 = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_opacity_set(comp_ImgButton1[UI_COMP_IMGBUTTON1_IMGBUTTON1], 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_opacity_set(comp_ImgButton1[UI_COMP_IMGBUTTON1_IMGBUTTON1], 100);
    }
}

// COMPONENT ImgButton1

lv_obj_t * ui_ImgButton1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ImgButton1;
    cui_ImgButton1 = lv_imgbtn_create(comp_parent);
    lv_obj_set_width(cui_ImgButton1, 177);
    lv_obj_set_height(cui_ImgButton1, 74);
    lv_obj_set_x(cui_ImgButton1, -5);
    lv_obj_set_y(cui_ImgButton1, 188);
    lv_obj_set_align(cui_ImgButton1, LV_ALIGN_CENTER);
    lv_obj_set_style_img_recolor(cui_ImgButton1, lv_color_hex(0xEF1414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(cui_ImgButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_IMGBUTTON1_NUM);
    children[UI_COMP_IMGBUTTON1_IMGBUTTON1] = cui_ImgButton1;
    lv_obj_add_event_cb(cui_ImgButton1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ImgButton1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_ImgButton1, ui_event_comp_ImgButton1_ImgButton1, LV_EVENT_ALL, children);
    ui_comp_ImgButton1_create_hook(cui_ImgButton1);
    return cui_ImgButton1;
}

