// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_rpmbackground_png);    // assets/rpmbackground.png
LV_IMG_DECLARE(ui_img_rpmfront_png);    // assets/rpmfront.png
LV_IMG_DECLARE(ui_img_rpmdial_png);    // assets/rpmdial.png
LV_IMG_DECLARE(ui_img_checkengine_png);    // assets/checkengine.png
LV_IMG_DECLARE(ui_img_watertemp_png);    // assets/watertemp.png
LV_IMG_DECLARE(ui_img_322054780);    // assets/0-100gauge.png
LV_IMG_DECLARE(ui_img_fuel_png);    // assets/fuel.png
LV_IMG_DECLARE(ui_img_dcs_png);    // assets/dcs.png
LV_IMG_DECLARE(ui_img_parkingbrake_png);    // assets/parkingbrake.png
LV_IMG_DECLARE(ui_img_turnsignal_png);    // assets/turnsignal.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
