// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: v4

#include "ui.h"

// COMPONENT rpmslider

lv_obj_t * ui_rpmslider_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_rpmslider;
    cui_rpmslider = lv_arc_create(comp_parent);
    lv_obj_set_width(cui_rpmslider, 150);
    lv_obj_set_height(cui_rpmslider, 150);
    lv_obj_set_align(cui_rpmslider, LV_ALIGN_CENTER);
    lv_arc_set_range(cui_rpmslider, 0, 9000);
    lv_arc_set_value(cui_rpmslider, 50);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_RPMSLIDER_NUM);
    children[UI_COMP_RPMSLIDER_RPMSLIDER] = cui_rpmslider;
    lv_obj_add_event_cb(cui_rpmslider, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_rpmslider, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_rpmslider_create_hook(cui_rpmslider);
    return cui_rpmslider;
}

