// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: v4

#include "ui.h"

lv_obj_t * uic_rpmslider;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_TopPanel = NULL;
lv_obj_t * ui_RPM = NULL;
lv_obj_t * ui_rpmbg = NULL;
lv_obj_t * ui_rpmslider = NULL;
lv_obj_t * ui_rpmscale = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_TopPanel, 800);
    lv_obj_set_height(ui_TopPanel, 480);
    lv_obj_set_align(ui_TopPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopPanel, lv_color_hex(0x2F2F2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM = lv_obj_create(ui_TopPanel);
    lv_obj_set_width(ui_RPM, 800);
    lv_obj_set_height(ui_RPM, 480);
    lv_obj_set_align(ui_RPM, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmbg = lv_image_create(ui_RPM);
    lv_image_set_src(ui_rpmbg, &ui_img_rpmbackground_png);
    lv_obj_set_width(ui_rpmbg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmbg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rpmbg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rpmbg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_rpmbg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rpmslider = lv_arc_create(ui_rpmbg);
    lv_obj_set_width(ui_rpmslider, 150);
    lv_obj_set_height(ui_rpmslider, 150);
    lv_obj_set_align(ui_rpmslider, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_rpmslider, 50);

    ui_rpmscale = lv_image_create(ui_RPM);
    lv_image_set_src(ui_rpmscale, &ui_img_rpmdial_png);
    lv_obj_set_width(ui_rpmscale, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmscale, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rpmscale, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rpmscale, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_rpmscale, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_rpmslider = ui_rpmslider;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_TopPanel = NULL;
    ui_RPM = NULL;
    ui_rpmbg = NULL;
    uic_rpmslider = NULL;
    ui_rpmslider = NULL;
    ui_rpmscale = NULL;

}
