// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: v4

#include "ui.h"

lv_obj_t * uic_rpmslider;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_rpmslider = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xD41212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmslider = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_rpmslider, 300);
    lv_obj_set_height(ui_rpmslider, 300);
    lv_obj_set_align(ui_rpmslider, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_rpmslider, 0, 1000);
    lv_arc_set_value(ui_rpmslider, 50);

    uic_rpmslider = ui_rpmslider;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_rpmslider = NULL;
    ui_rpmslider = NULL;

}
